#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright 2016 Silvio Peroni <essepuntato@gmail.com>
# Copyright 2020 Fabio Mariani <fabio.mariani555@gmail.com>
# Copyright 2022 Arcangelo Massari <arcangelo.massari@unibo.it>
#
# Permission to use, copy, modify, and/or distribute this software for any purpose
# with or without fee is hereby granted, provided that the above copyright notice
# and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED 'AS IS' AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
# FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT,
# OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE,
# DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS
# ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS
# SOFTWARE.

# Mandatory settings

# Endpoint URL to load the output RDF
triplestore_url: http://localhost:19999/blazegraph/sparql
# A support folder to save counters of the various types of entities. It must not be deleted or moved until the end of the Meta process
info_dir: C:/Users/arcangelo.massari2/OneDrive - Alma Mater Studiorum Università di Bologna/Desktop/meta_output/output/info_dir
# A URI string representing the provenance agent which is considered responsible for the RDF graph manipulation
resp_agent: https://orcid.org/0000-0002-8420-0696
# Directory where raw CSV files are stored
input_csv_dir: C:/Users/arcangelo.massari2/OneDrive - Alma Mater Studiorum Università di Bologna/Desktop/meta_output/meta_input
# Directory where cleaned CSV files will be stored
output_csv_dir: C:/Users/arcangelo.massari2/OneDrive - Alma Mater Studiorum Università di Bologna/Desktop/meta_output/output/csv
# Directory where both output RDF data and provenance files will be stored
output_rdf_dir: C:/Users/arcangelo.massari2/OneDrive - Alma Mater Studiorum Università di Bologna/Desktop/meta_output/output/rdf
# Indices are products of the CSV cleaning step, and they are necessary for RDF files' creation
indexes_dir: C:/Users/arcangelo.massari2/OneDrive - Alma Mater Studiorum Università di Bologna/Desktop/meta_output/output/indexes
# Path of a text file containing a list of processed CSVs. It will be created if it doesn't exist. This file is helpful to avoid repeating the process twice for the same file
cache_path: C:/Users/arcangelo.massari2/OneDrive - Alma Mater Studiorum Università di Bologna/Desktop/meta_output/output/cache.txt

# Optional settings

# The base URI of entities on Meta. This setting can be safely left as is
base_iri: https://w3id.org/oc/meta/
# URL where the namespaces and prefixes used in the OpenCitations Data Model are defined. This setting can be safely left as is
context_path: https://w3id.org/oc/corpus/context.json
# Number of files per folder. dir_split_number's value must be multiple of items_per_file's value. This parameter is useful only if you choose to return the output in json-ld format
dir_split_number: 10000
# Number of items per file. This parameter is useful only if you choose to return the output in json-ld format
items_per_file: 1000
default_dir: _
# A prefix for the sequential number in entities’ URIs. This setting can be safely left as is
supplier_prefix: '060'
# If True, save all the graphset and provset in one file, and save all the graphset on the triplestore. 
# If False, the graphs are saved according to the usual OpenCitations strategy (the "complex" hierarchy of folders and subfolders for each type of entity)
rdf_output_in_chunks: False
# Data source URL. This setting can be safely left as is
source: https://api.crossref.org/
# If True, use the DOI API service to check if DOIs are valid
use_doi_api_service: False
# If True, the Meta software runs in multiprocess
run_in_multiprocess: True
# Show a loading bar, elapsed time and estimated time
verbose: True

