# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run the tests
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  CheckCoverage:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3.0.2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip3 install poetry
        poetry install
        poetry run pip3 install coverage
        poetry run pip3 install coverage-badge
    - name: Run Blazegraph
      run: |
        wget https://github.com/blazegraph/database/releases/download/BLAZEGRAPH_2_1_6_RC/blazegraph.jar
        java -server -jar blazegraph.jar &
        python3 -c 'import time; time.sleep(10)'
        curl -X POST  http://localhost:9999/blazegraph/namespace/kb/textIndex?force-index-create=true
    - name: Check the overage
      run: poetry run coverage run -m unittest discover -s test -p *_test.py
    - name: Generate the badge
      run: |
        mv .coverage test/coverage/
        cd test/coverage/
        rm coverage.svg
        poetry run coverage-badge -o coverage.svg
    - name: Publish the badge on the GitHub repo
      run: |
        ls
        git add .coverage
        git add coverage.svg
        git config --global user.name 'arcangelo7'
        git config --global user.email 'arcangelomas@gmail.com'
        git commit -m 'Coverage updated'
        git push
